/**
 * DOM tests for Composer.tsx.
 * Covers:
 *   - The model and effort menu (kit Menu): the trigger reads the model and
 *     effort as text; picking a model, an effort or a provider reports it.
 *   - The send button: grey and disabled until there is something to send.
 *   - SlashMenu: Escape dismisses the menu without wiping the draft.
 *
 * Uses react-dom/client + happy-dom (via bunfig.toml preload).
 * Pattern follows src/lib/toast.dom.test.tsx.
 */
import { afterEach, beforeEach, describe, expect, mock, test } from 'bun:test';
import React, { createRef } from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Composer, ComposerProps } from './Composer';
import { ProviderOption, ModelOption } from '../../lib/provider-models';

// Mounting Composer also mounts MicButton/VoiceSettings, whose useVoiceInput/
// useOriginPosture hooks fire real background react-query reads (voice.status,
// config.get, voice.wake.status, pairing.posture.get) on every render, wholly
// incidental to what these ModelPicker/SlashMenu tests exercise. Left un-stubbed,
// those reads hit the real GOODVIBES_BASE_URL (nothing listening in a test
// environment), and a real refused connection leaves Bun's fetch/http-compat
// internals with a dangling rejection that can surface asynchronously, outside any
// promise this file holds a handle to, sometimes well after a given test (or this
// file) finishes running. See src/lib/auth-token.test.ts's header comment for the
// full mechanism; this file hits the same seam through a different call path.
//
// The components already tolerate these background reads failing (nothing here
// asserts on voice/config/posture state), so the stub reproduces that same
// "daemon unreachable" outcome, only in-process, no socket, no async gap left
// dangling after the test that opened it.
const realFetch = globalThis.fetch;

function rejectingFetchStub(): typeof fetch {
  const impl = async (): Promise<Response> => {
    throw new Error('daemon unreachable (test stub: no real network in tests)');
  };
  return Object.assign(impl, { preconnect: realFetch.preconnect }) as unknown as typeof fetch;
}

beforeEach(() => {
  globalThis.fetch = rejectingFetchStub();
});

// The composer now hosts the voice controls (mic + voice settings), which read
// voice.status/config.get through react-query, exactly as the real app does under its
// app-wide QueryClientProvider. Wrap renders in a throwaway client (no retry/refetch) so
// these ModelPicker/SlashMenu tests exercise the composer with its real dependency tree.
function makeTestQueryClient(): QueryClient {
  return new QueryClient({ defaultOptions: { queries: { retry: false, refetchOnWindowFocus: false } } });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const noop = () => {};

/**
 * querySelector by [id="value"], avoids CSS.escape which is absent in
 * happy-dom. IDs generated by React's useId() contain colons and other
 * chars that require escaping in CSS selectors.
 */
function byId(root: ParentNode, id: string): Element | null {
  return root.querySelector(`[id="${id}"]`);
}

// ---------------------------------------------------------------------------
// Shared stubs
// ---------------------------------------------------------------------------

const PROVIDERS: ProviderOption[] = [
  { id: 'openai', label: 'OpenAI', value: {} },
];

const MODELS: ModelOption[] = [
  { id: 'openai:gpt-a', label: 'GPT-A', value: {}, providerId: 'openai', rawModelId: 'gpt-a', registryKey: 'openai:gpt-a' },
  { id: 'openai:gpt-b', label: 'GPT-B', value: {}, providerId: 'openai', rawModelId: 'gpt-b', registryKey: 'openai:gpt-b' },
  { id: 'openai:gpt-c', label: 'GPT-C', value: {}, providerId: 'openai', rawModelId: 'gpt-c', registryKey: 'openai:gpt-c' },
];

const SLASH_COMMANDS = [
  { name: 'help', description: 'Show help' },
  { name: 'clear', description: 'Clear history' },
  { name: 'compact', description: 'Compact mode' },
];

function makeProps(overrides: Partial<ComposerProps> = {}): ComposerProps {
  return {
    draft: '',
    attachedFiles: [],
    isSendPending: false,
    sendError: null,
    turnError: '',
    renameSessionError: null,
    selectModelError: null,
    providerOptions: PROVIDERS,
    selectedProviderId: 'openai',
    providerModelOptions: MODELS,
    selectedModelRegistryKey: 'openai:gpt-a',
    selectModelPending: false,
    composerRef: createRef<HTMLTextAreaElement | null>(),
    fileInputRef: createRef<HTMLInputElement | null>(),
    onDraftChange: noop,
    onComposerKeyDown: noop,
    onSubmit: noop,
    onFileSelection: noop,
    onRemoveAttachedFile: noop,
    onProviderChange: noop,
    onModelChange: noop,
    slashCommands: SLASH_COMMANDS,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Render helpers
// ---------------------------------------------------------------------------

function mountComposer(props: ComposerProps) {
  const container = document.createElement('div');
  document.body.appendChild(container);
  const root = createRoot(container);
  const client = makeTestQueryClient();
  flushSync(() => {
    root.render(
      <QueryClientProvider client={client}>
        <Composer {...props} />
      </QueryClientProvider>,
    );
  });
  return {
    container,
    rerender(nextProps: ComposerProps) {
      flushSync(() => {
        root.render(
          <QueryClientProvider client={client}>
            <Composer {...nextProps} />
          </QueryClientProvider>,
        );
      });
    },
    unmount() {
      flushSync(() => root.unmount());
      container.parentNode?.removeChild(container);
    },
  };
}

afterEach(() => {
  globalThis.fetch = realFetch;
  document.body.innerHTML = '';
});

// ---------------------------------------------------------------------------
// Model and effort menu (the kit Menu, portalled to document.body)
// ---------------------------------------------------------------------------

function openModelMenu(container: HTMLElement): HTMLElement {
  const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn');
  expect(trigger).not.toBeNull();
  flushSync(() => trigger!.click());
  const menu = document.body.querySelector<HTMLElement>('[role="menu"][aria-label="Model and effort"]');
  expect(menu).not.toBeNull();
  return menu!;
}

function menuItem(menu: HTMLElement, text: string): HTMLButtonElement | undefined {
  return Array.from(menu.querySelectorAll<HTMLButtonElement>('[role="menuitem"]'))
    .find((item) => item.querySelector('.gv-menu-item__label')?.textContent === text);
}

describe('model and effort menu', () => {
  test('the trigger reads the model and the effort as text', () => {
    const { container, unmount } = mountComposer(makeProps({
      effortLevels: ['low', 'medium', 'high'],
      currentEffort: 'medium',
      onEffortChange: noop,
    }));
    const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn')!;
    expect(trigger.querySelector('.composer-model-label')?.textContent).toBe('GPT-A');
    expect(trigger.querySelector('.composer-model-effort')?.textContent).toBe('Medium');
    expect(trigger.getAttribute('aria-label')).toBe('Model: GPT-A, effort Medium');
    expect(trigger.getAttribute('aria-haspopup')).toBe('menu');
    unmount();
  });

  test('picking a model reports its registryKey and closes the menu', () => {
    const picked: string[] = [];
    const { container, unmount } = mountComposer(makeProps({ onModelChange: (key) => picked.push(key) }));
    const menu = openModelMenu(container);
    // The current model is marked for assistive tech, not by color alone.
    expect(menuItem(menu, 'GPT-A')?.textContent).toContain('(selected)');
    expect(menuItem(menu, 'GPT-B')?.textContent).not.toContain('(selected)');
    flushSync(() => menuItem(menu, 'GPT-B')!.click());
    expect(picked).toEqual(['openai:gpt-b']);
    expect(document.body.querySelector('[role="menu"][aria-label="Model and effort"]')).toBeNull();
    unmount();
  });

  test('the menu lists only model rows when there is one provider and no effort ladder', () => {
    const { container, unmount } = mountComposer(makeProps());
    const menu = openModelMenu(container);
    const labels = Array.from(menu.querySelectorAll('[role="menuitem"] .gv-menu-item__label')).map((el) => el.textContent);
    expect(labels).toEqual(['GPT-A', 'GPT-B', 'GPT-C']);
    unmount();
  });

  test('with more than one provider, choosing a provider reports it and keeps the menu open', () => {
    const switched: string[] = [];
    const { container, unmount } = mountComposer(makeProps({
      providerOptions: [...PROVIDERS, { id: 'anthropic', label: 'Anthropic', value: {} }],
      onProviderChange: (id) => switched.push(id),
    }));
    const menu = openModelMenu(container);
    flushSync(() => menuItem(menu, 'Anthropic')!.click());
    expect(switched).toEqual(['anthropic']);
    expect(document.body.querySelector('[role="menu"][aria-label="Model and effort"]')).not.toBeNull();
    unmount();
  });

  test('no providers: the trigger is disabled and says so', () => {
    const { container, unmount } = mountComposer(makeProps({ providerOptions: [], providerModelOptions: [] }));
    const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn')!;
    expect(trigger.disabled).toBe(true);
    expect(trigger.textContent).toContain('No models');
    unmount();
  });
});

describe('send button', () => {
  test('grey and disabled until there is something to send', () => {
    const { container, unmount } = mountComposer(makeProps({ draft: '   ' }));
    const send = container.querySelector<HTMLButtonElement>('.send-button')!;
    expect(send.disabled).toBe(true);
    expect(send.getAttribute('data-ready')).toBeNull();
    unmount();
  });

  test('ready (light) once the draft has text', () => {
    const { container, unmount } = mountComposer(makeProps({ draft: 'hello' }));
    const send = container.querySelector<HTMLButtonElement>('.send-button')!;
    expect(send.disabled).toBe(false);
    expect(send.getAttribute('data-ready')).toBe('true');
    unmount();
  });

  test('ready with an attachment and no text', () => {
    const file = new File(['x'], 'notes.txt', { type: 'text/plain' });
    const { container, unmount } = mountComposer(makeProps({ attachedFiles: [file] }));
    expect(container.querySelector('.send-button')!.getAttribute('data-ready')).toBe('true');
    unmount();
  });
});

describe('placeholder and accessible name', () => {
  test('the visible placeholder can change while the accessible name stays "Message GoodVibes"', () => {
    const { container, unmount } = mountComposer(makeProps({ placeholder: 'Ask GoodVibes anything', layout: 'centered' }));
    const textarea = container.querySelector('textarea')!;
    expect(textarea.getAttribute('placeholder')).toBe('Ask GoodVibes anything');
    expect(textarea.getAttribute('aria-label')).toBe('Message GoodVibes');
    expect(container.querySelector('form.composer--centered')).not.toBeNull();
    unmount();
  });
});

describe('SlashMenu keyboard behaviour', () => {
  test('Escape dismisses slash menu without calling onDraftChange', () => {
    const onDraftChange = mock((_v: string) => {});
    const draft = '/he';
    const { container, rerender, unmount } = mountComposer(
      makeProps({ draft, onDraftChange }),
    );

    // Slash menu should be visible with draft='/he'
    const menu = container.querySelector('.composer-slash-menu');
    expect(menu).not.toBeNull();

    // Escape in the textarea
    const textarea = container.querySelector<HTMLTextAreaElement>('textarea');
    expect(textarea).not.toBeNull();
    flushSync(() =>
      textarea!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }),
      ),
    );

    // onDraftChange must NOT have been called (draft is not wiped)
    expect(onDraftChange).not.toHaveBeenCalled();

    // Re-render with the same draft (parent keeps it)
    rerender(makeProps({ draft, onDraftChange }));

    // Menu should be gone now
    const menuAfter = container.querySelector('.composer-slash-menu');
    expect(menuAfter).toBeNull();

    unmount();
  });

  test('dismissed menu reappears after draft moves to non-slash then back to slash', () => {
    const onDraftChange = mock((_v: string) => {});
    const { container, rerender, unmount } = mountComposer(
      makeProps({ draft: '/he', onDraftChange }),
    );

    // Escape to dismiss
    const textarea = container.querySelector<HTMLTextAreaElement>('textarea');
    flushSync(() =>
      textarea!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }),
      ),
    );

    // Move to non-slash draft, then back to slash
    rerender(makeProps({ draft: 'hello', onDraftChange }));
    rerender(makeProps({ draft: '/cl', onDraftChange }));

    const menu = container.querySelector('.composer-slash-menu');
    expect(menu).not.toBeNull();

    unmount();
  });

  test('textarea aria-activedescendant points to an existing option element', () => {
    const draft = '/';
    const { container, unmount } = mountComposer(makeProps({ draft }));

    const textarea = container.querySelector<HTMLTextAreaElement>('textarea');
    expect(textarea).not.toBeNull();

    const activeDescendant = textarea!.getAttribute('aria-activedescendant');
    expect(activeDescendant).toBeTruthy();

    const activeEl = byId(container, activeDescendant!);
    expect(activeEl).not.toBeNull();
    expect(activeEl!.getAttribute('role')).toBe('option');

    unmount();
  });
});

describe('effort in the model menu', () => {
  test('renders the ladder (with Default) when the model reports 2+ levels, and reports the change', () => {
    const changes: string[] = [];
    const { container, unmount } = mountComposer(makeProps({
      effortLevels: ['low', 'medium', 'high'],
      currentEffort: 'medium',
      onEffortChange: (effort) => changes.push(effort),
    }));
    const menu = openModelMenu(container);
    expect(menu.textContent).toContain('Effort');
    expect(menuItem(menu, 'Medium')?.textContent).toContain('(selected)');
    flushSync(() => menuItem(menu, 'High')!.click());
    expect(changes).toEqual(['high']);
    unmount();
  });

  test('Default clears the level (reports an empty string)', () => {
    const changes: string[] = [];
    const { container, unmount } = mountComposer(makeProps({
      effortLevels: ['low', 'high'],
      currentEffort: 'high',
      onEffortChange: (effort) => changes.push(effort),
    }));
    const menu = openModelMenu(container);
    flushSync(() => menuItem(menu, 'Default')!.click());
    expect(changes).toEqual(['']);
    unmount();
  });

  test('absent levels (older daemon) render no effort section or effort text at all', () => {
    const { container, unmount } = mountComposer(makeProps({}));
    expect(container.querySelector('.composer-model-effort')).toBeNull();
    const menu = openModelMenu(container);
    expect(menuItem(menu, 'Default')).toBeUndefined();
    unmount();
  });

  test('a single-level ladder renders no effort choice: there is nothing to choose', () => {
    const { container, unmount } = mountComposer(makeProps({ effortLevels: ['medium'], currentEffort: 'medium', onEffortChange: noop }));
    expect(container.querySelector('.composer-model-effort')).toBeNull();
    const menu = openModelMenu(container);
    expect(menuItem(menu, 'Medium')).toBeUndefined();
    unmount();
  });
});
