/**
 * DOM tests for Composer.tsx.
 * Covers:
 *   - ModelPicker keyboard navigation: aria-activedescendant advances,
 *     Enter selects the highlighted item.
 *   - SlashMenu: Escape dismisses the menu without wiping the draft.
 *
 * Uses react-dom/client + happy-dom (via bunfig.toml preload).
 * Pattern follows src/lib/toast.dom.test.tsx.
 */
import { afterEach, describe, expect, mock, test } from 'bun:test';
import React, { createRef } from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Composer, ComposerProps } from './Composer';
import { ProviderOption, ModelOption } from '../../lib/provider-models';

// The composer now hosts the voice controls (mic + voice settings), which read
// voice.status/config.get through react-query — exactly as the real app does under its
// app-wide QueryClientProvider. Wrap renders in a throwaway client (no retry/refetch) so
// these ModelPicker/SlashMenu tests exercise the composer with its real dependency tree.
function makeTestQueryClient(): QueryClient {
  return new QueryClient({ defaultOptions: { queries: { retry: false, refetchOnWindowFocus: false } } });
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const noop = () => {};

/**
 * querySelector by [id="value"] — avoids CSS.escape which is absent in
 * happy-dom. IDs generated by React's useId() contain colons and other
 * chars that require escaping in CSS selectors.
 */
function byId(root: ParentNode, id: string): Element | null {
  return root.querySelector(`[id="${id}"]`);
}

// ---------------------------------------------------------------------------
// Shared stubs
// ---------------------------------------------------------------------------

const PROVIDERS: ProviderOption[] = [
  { id: 'openai', label: 'OpenAI', value: {} },
];

const MODELS: ModelOption[] = [
  { id: 'openai:gpt-a', label: 'GPT-A', value: {}, providerId: 'openai', rawModelId: 'gpt-a', registryKey: 'openai:gpt-a' },
  { id: 'openai:gpt-b', label: 'GPT-B', value: {}, providerId: 'openai', rawModelId: 'gpt-b', registryKey: 'openai:gpt-b' },
  { id: 'openai:gpt-c', label: 'GPT-C', value: {}, providerId: 'openai', rawModelId: 'gpt-c', registryKey: 'openai:gpt-c' },
];

const SLASH_COMMANDS = [
  { name: 'help', description: 'Show help' },
  { name: 'clear', description: 'Clear history' },
  { name: 'compact', description: 'Compact mode' },
];

function makeProps(overrides: Partial<ComposerProps> = {}): ComposerProps {
  return {
    draft: '',
    attachedFiles: [],
    isSendPending: false,
    sendError: null,
    turnError: '',
    renameSessionError: null,
    selectModelError: null,
    providerOptions: PROVIDERS,
    selectedProviderId: 'openai',
    providerModelOptions: MODELS,
    selectedModelRegistryKey: 'openai:gpt-a',
    selectModelPending: false,
    composerRef: createRef<HTMLTextAreaElement | null>(),
    fileInputRef: createRef<HTMLInputElement | null>(),
    onDraftChange: noop,
    onComposerKeyDown: noop,
    onSubmit: noop,
    onFileSelection: noop,
    onRemoveAttachedFile: noop,
    onProviderChange: noop,
    onModelChange: noop,
    slashCommands: SLASH_COMMANDS,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Render helpers
// ---------------------------------------------------------------------------

function mountComposer(props: ComposerProps) {
  const container = document.createElement('div');
  document.body.appendChild(container);
  const root = createRoot(container);
  const client = makeTestQueryClient();
  flushSync(() => {
    root.render(
      <QueryClientProvider client={client}>
        <Composer {...props} />
      </QueryClientProvider>,
    );
  });
  return {
    container,
    rerender(nextProps: ComposerProps) {
      flushSync(() => {
        root.render(
          <QueryClientProvider client={client}>
            <Composer {...nextProps} />
          </QueryClientProvider>,
        );
      });
    },
    unmount() {
      flushSync(() => root.unmount());
      container.parentNode?.removeChild(container);
    },
  };
}

afterEach(() => {
  document.body.innerHTML = '';
});

// ---------------------------------------------------------------------------
// ModelPicker keyboard navigation
// ---------------------------------------------------------------------------

describe('ModelPicker keyboard navigation', () => {
  test('ArrowDown moves aria-activedescendant to the first option', () => {
    const { container, unmount } = mountComposer(makeProps());

    // Open the picker via click on the trigger button
    const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn');
    expect(trigger).not.toBeNull();
    flushSync(() => trigger!.click());

    const popover = container.querySelector<HTMLDivElement>('[role="listbox"]');
    expect(popover).not.toBeNull();

    // Fire ArrowDown on the popover (bubbles so React event delegation picks it up)
    flushSync(() =>
      popover!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }),
      ),
    );

    // aria-activedescendant must be set and point to an existing element
    const activeId = popover!.getAttribute('aria-activedescendant');
    expect(activeId).toBeTruthy();
    const activeEl = byId(container, activeId!);
    expect(activeEl).not.toBeNull();
    expect(activeEl!.getAttribute('data-active')).toBe('true');

    unmount();
  });

  test('two ArrowDown events advance to the second option', () => {
    const { container, unmount } = mountComposer(makeProps());

    const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn');
    flushSync(() => trigger!.click());

    const popover = container.querySelector<HTMLDivElement>('[role="listbox"]');
    expect(popover).not.toBeNull();

    flushSync(() =>
      popover!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }),
      ),
    );
    flushSync(() =>
      popover!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }),
      ),
    );

    const activeId = popover!.getAttribute('aria-activedescendant');
    expect(activeId).toBeTruthy();
    const activeEl = byId(container, activeId!);
    // Index 1 = GPT-B (0-based: first ArrowDown goes to 0, second goes to 1)
    expect(activeEl?.textContent).toContain('GPT-B');

    unmount();
  });

  test('Enter on highlighted option calls onModelChange with its registryKey', () => {
    const onModelChange = mock((_key: string) => {});
    const { container, unmount } = mountComposer(makeProps({ onModelChange }));

    // Open picker
    const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn');
    flushSync(() => trigger!.click());

    const popover = container.querySelector<HTMLDivElement>('[role="listbox"]');
    expect(popover).not.toBeNull();

    // Move to first model option (activeIndex becomes 0)
    flushSync(() =>
      popover!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }),
      ),
    );
    // Press Enter to select
    flushSync(() =>
      popover!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }),
      ),
    );

    expect(onModelChange).toHaveBeenCalledTimes(1);
    const calledWith = (onModelChange.mock.calls[0] as [string])[0];
    expect(MODELS.map((m) => m.registryKey)).toContain(calledWith);

    unmount();
  });

  test('listbox contains only model options, not provider headers', () => {
    const { container, unmount } = mountComposer(makeProps());

    const trigger = container.querySelector<HTMLButtonElement>('.composer-model-btn');
    flushSync(() => trigger!.click());

    const popover = container.querySelector<HTMLDivElement>('[role="listbox"]');
    expect(popover).not.toBeNull();

    // Only model buttons should have role=option
    const options = popover!.querySelectorAll<HTMLElement>('[role="option"]');
    // Provider header buttons must NOT have role=option
    for (const opt of Array.from(options)) {
      expect(opt.classList.contains('composer-model-provider-btn')).toBe(false);
    }
    // One option per model
    expect(options.length).toBe(MODELS.length);

    unmount();
  });
});

// ---------------------------------------------------------------------------
// SlashMenu keyboard behaviour
// ---------------------------------------------------------------------------

describe('SlashMenu keyboard behaviour', () => {
  test('Escape dismisses slash menu without calling onDraftChange', () => {
    const onDraftChange = mock((_v: string) => {});
    const draft = '/he';
    const { container, rerender, unmount } = mountComposer(
      makeProps({ draft, onDraftChange }),
    );

    // Slash menu should be visible with draft='/he'
    const menu = container.querySelector('.composer-slash-menu');
    expect(menu).not.toBeNull();

    // Escape in the textarea
    const textarea = container.querySelector<HTMLTextAreaElement>('textarea');
    expect(textarea).not.toBeNull();
    flushSync(() =>
      textarea!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }),
      ),
    );

    // onDraftChange must NOT have been called (draft is not wiped)
    expect(onDraftChange).not.toHaveBeenCalled();

    // Re-render with the same draft (parent keeps it)
    rerender(makeProps({ draft, onDraftChange }));

    // Menu should be gone now
    const menuAfter = container.querySelector('.composer-slash-menu');
    expect(menuAfter).toBeNull();

    unmount();
  });

  test('dismissed menu reappears after draft moves to non-slash then back to slash', () => {
    const onDraftChange = mock((_v: string) => {});
    const { container, rerender, unmount } = mountComposer(
      makeProps({ draft: '/he', onDraftChange }),
    );

    // Escape to dismiss
    const textarea = container.querySelector<HTMLTextAreaElement>('textarea');
    flushSync(() =>
      textarea!.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }),
      ),
    );

    // Move to non-slash draft, then back to slash
    rerender(makeProps({ draft: 'hello', onDraftChange }));
    rerender(makeProps({ draft: '/cl', onDraftChange }));

    const menu = container.querySelector('.composer-slash-menu');
    expect(menu).not.toBeNull();

    unmount();
  });

  test('textarea aria-activedescendant points to an existing option element', () => {
    const draft = '/';
    const { container, unmount } = mountComposer(makeProps({ draft }));

    const textarea = container.querySelector<HTMLTextAreaElement>('textarea');
    expect(textarea).not.toBeNull();

    const activeDescendant = textarea!.getAttribute('aria-activedescendant');
    expect(activeDescendant).toBeTruthy();

    const activeEl = byId(container, activeDescendant!);
    expect(activeEl).not.toBeNull();
    expect(activeEl!.getAttribute('role')).toBe('option');

    unmount();
  });
});
